server:
  port: 5000
  max-http-header-size: 10000000
  servlet:
    context-path: /
    session:
      cookie:
        name: qiantaoyun
spring:
  datasource:
    druid:
      url: jdbc:postgresql://192.168.125.130:5432/qiantaoyundemo
      username: postgres
      password: qiantaoyun112
      driver-class-name: org.postgresql.Driver
flowable:
  async-executor-activate: false
